version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'

builds:
  - id: build
    binary: filter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    ldflags:
      - -s -w -extldflags "-static"
      - -X main.version={{ .Tag }}
      - -X main.commit={{.Commit}}

archives:
  - id: filter
    format: tar.gz
    name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

release:
  github:
    owner: '{{ .Env.GITHUB_REPOSITORY_OWNER }}'
    name: '{{ .Env.GITHUB_REPOSITORY_NAME }}'
  name_template: 'v{{ .Version }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
