# .ko.yaml
baseImageOverrides:
  linux/arm/v6: gcr.io/distroless/static:nonroot
  linux/arm/v7: gcr.io/distroless/static:nonroot

defaultPlatform: linux/amd64
platforms:
  - linux/amd64
  - linux/arm64
  - linux/arm/v7
  - linux/arm/v6
